name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        with:
          github_user_name: Yekta-Ramzannasab
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg
          color_snake: '#0077FF,#ffffff'   
          color_dots: '#CCCCCC,#1E90FF,#FFFFFF,#ADD8E6'
      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
